# This starter workflow is for a CMake project running on a single platform (Ubuntu in this case).
# For cross-platform coverage, refer to: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml

name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The build job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # This step checks out the repository code to the GitHub Actions runner.

    - name: Set up CMake
      uses: actions/setup-cmake@v3
      with:
        cmake-version: '3.21'  # You can specify the required CMake version here.

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build build --config ${env.BUILD_TYPE}

    - name: Test
      working-directory: build
      # Execute tests defined by the CMake configuration.
      run: ctest --config ${env.BUILD_TYPE}
